### ISSUE TITLE
It does not work in IIS express.

### ISSUE THREAD

**Issue by hardhub** [kmaragon/Konscious.Security.Cryptography#11]
It is very strange... inside console app it works fine.
But in IIS Express it is simply timed out.

**Comment by WouterJanson** [comment]
I had the same sort of issues, where the code would lock and it would never return a hash.

A simple temporary workaround would be to put the code in a separate method and call it as a task with `TaskCreationOptions.LongRunning`. 

For example:
``` C#
Task.Factory.StartNew(() => { hash = YourCryptMethod(password, salt); },TaskCreationOptions.LongRunning).Wait();
```

I've made a PR (#10) which could fix these problems.

**Comment by maxim-boligatov** [comment]
> I had the same sort of issues, where the code would lock and it would never return a hash.
Absolutely agree...

It was a reason why PDKDF2 - HMACSHA512 with very big amount of iterations is finally used instead of Argon2.

> Task.WhenAll(segment).ConfigureAwait(false);
Why we cannot restore context? And what does it mean from point of view of implementation of Argon2 algorithm?
I guess you made it work... but are you believe it is the correct fix?

**Comment by smarts** [comment]
@hardhub can I ask why you're using IIS Express for .NET Core development instead of Kestrel?

**Comment by hardhub** [comment]
@smarts 

> can I ask why you're using IIS Express for .NET Core development instead of Kestrel?

That project is not .Net Core project.    
Kestrel is not available option in IDE.    
And IIS Express is default and it fully meets development needs.

**Comment by smarts** [comment]
Ah ok, thanks for clarifying.

**Comment by kmaragon** [comment]
I merged the PR for now. I think I could give an easy way to avert the problem in .NET 4.5+ by exposing this all in an async method. Then the calling code could use that in an async / await context and expose it as such all the way up at the controller level. As I understand it, that should also help the issue as the initial thread from IIS can get back to doing work for IIS.

**Comment by kmaragon** [comment]
So this update might break you a bit. But if you switch from `GetBytes` to `GetBytesAsync` you can `ConfigureAwait` directly on that. Alternatively, you could expose the endpoint on the controller as async, using await on the GetBytesAsync result and IIS (or really ASP.NET inside of IIS) should handle the Context issues.

**Comment by kmaragon** [comment]
I'm going to close this issue as I haven't heard anything since the update
