### ISSUE TITLE
NuGet package is wrong

### ISSUE THREAD

**Issue by meh-uk** [kmaragon/Konscious.Security.Cryptography#16]
Hey

Your Nuget package is missing dependencies on:
* System.Runtime
* System.Runtime.Extensions
* System.Resources.ResourceManager
* System.Globalization

**Comment by kmaragon** [comment]
Could you elaborate a bit?

The package doesn't actually use any of these. It uses System.Runtime.InteropServices but that one isn't listed here.

**Comment by meh-uk** [comment]
I think the Vector.IsHardwareAccelerated isn't included in .NET 4.5.2. Perhaps it all works fine with .NET 4.6 which unfortunately we aren't using :(.

**Comment by kmaragon** [comment]
It's not. But in theory, the nuget package should support 4.5.2:

https://www.nuget.org/packages/System.Numerics.Vectors

This is referenced as 4.* in the nuget package. So it should get the latest System.Numerics.Vectors package which should support >= .NET 4.5

It will not, however, support anything older

**Comment by kmaragon** [comment]
Maybe 4.* is resolving the preview release? 4.4.x? Which is >= 4.6

**Comment by kmaragon** [comment]
I'll close this as I'm guessing it was probably a nuget config that is explicitly using experimental packages. With that said, I'll change the version tag to 4.3.* on the next publish, knowing that newer versions of the .NET libraries are going to break compatibility with 4.5.2 when they're released as stable.
