### ISSUE TITLE
Deadlock in synchronous GetBytes(int) method

### ISSUE THREAD

**Issue by MaxBarraclough** [kmaragon/Konscious.Security.Cryptography#22]
Under certain configurations, `GetBytes(int)` will deadlock. I've just had this happen to my ASP.Net code.

I believe this is because it contains an anti-pattern that Stephen Cleary describes and explains in his [Don't Block on Async Code](http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html) blog post.

Specifically the line https://github.com/kmaragon/Konscious.Security.Cryptography/blob/14d35c9/Konscious.Security.Cryptography.Argon2/Argon2.cs#L31

A workaround is to use the Task class to execute on the thread-pool while the calling thread waits, avoiding the deadlock:

```
var task = System.Threading.Tasks.Task.Run(async () =>
{
    var a = new Konscious.Security.Cryptography.Argon2i(...);
    a.DegreeOfParallelism = ...;
    a.MemorySize = ...;
    a.Iterations = ...;
    a.Salt = ...;
    byte[] h = await a.GetBytesAsync(...);
    return h;
});
var hh = task.Result;
```

Or, slightly more simply:

```
var task = System.Threading.Tasks.Task.Run( () =>
{
    var a = new Konscious.Security.Cryptography.Argon2i(...);
    a.DegreeOfParallelism = ...;
    a.MemorySize = ...;
    a.Iterations = ...;
    a.Salt = ...;
    Task<byte[]> h = a.GetBytesAsync(...);
    return h;
});
var hh = task.Result;
```

Is there really any need for an async version of the method? It's CPU-bound anyway, after all.

**Comment by charliefoxtwo** [comment]
Chiming in to confirm I have the same issue, also in ASP.NET. Implementing @MaxBarraclough 's solution seems to work.

**Comment by tbandixen** [comment]
Chiming in to confirm that the issue in WPF exists too. Implementing @MaxBarraclough 's workaround works.

**Comment by kmaragon** [comment]
Actually the async version of the method was exactly for this use case. It was to give the caller the flexibility to avoid this bug. 

When you call `task.Result`, you are re-introducing the exact issue cited in the post you linked to. But it's easy to get around with `task.ConfigureAwait(false)` before you call Result. I haven't released a new version in a long time. But my plan was to make that the default for the synchronous method. But the async method would let the user decide. In the web API case, if you make the Web API function itself async and return the task, you shouldn't have this issue anymore.

**Comment by kmaragon** [comment]
Updated comments above

**Comment by MaxBarraclough** [comment]
Hi Keef. Thanks for the reply, but I think you misread me.


> The issue raised in the article is not in the Argon2 library.

Yes it is. The deadlock was occurring when my purely synchronous ASP.Net code called Argon2's synchronous `GetBytes` method, which contains the bug.


> Because it's redoing the exact thing my synchronous method was doing that was causing issues for people.

Not so. My workaround works for charliefoxtwo, tbandixen, and myself. It is not the equivalent of the synchronous `GetBytes` method, as it executes on the thread-pool but blocks the caller thread, following Stephen Toub's *Offload to Another Thread* pattern, documented in [Should I expose synchronous wrappers for asynchronous methods?](https://blogs.msdn.microsoft.com/pfxteam/2012/04/13/should-i-expose-synchronous-wrappers-for-asynchronous-methods/)

I agree that a `ConfigureAwait(false)` call would be good practice in the first code-fragment I gave - oops! It works fine without it though, and I don't think it's strictly needed, looking at Toub's article.

> Which it does, in a way that causes deadlocks for the exact same reason that the code above does.

Again, and at the risk of labouring the point: my workaround doesn't deadlock, only the synchronous `GetBytes` method does.

**Comment by kmaragon** [comment]
I see. I read the code sample above as repro steps. A more simple way to accomplish this is to instead say:
```
    var a = new Konscious.Security.Cryptography.Argon2i(...);
    a.DegreeOfParallelism = ...;
    a.MemorySize = ...;
    a.Iterations = ...;
    a.Salt = ...;
    var h = a.GetBytesAsync(...);
    h.ConfigureAwait(false);
    return h.result;
```
But again, just having an async method all the way up the call chain is a better approach.

And to your point, it is indeed problematic to expose a synchronous wrapper for an Aynch method. But that bumps up against the fact that the GetBytes method is from the base class (DeriveBytes)[https://msdn.microsoft.com/en-us/library/system.security.cryptography.derivebytes(v=vs.110).aspx]. Which doesn't seem to consider a cryptographic algorithm that's distinctly multi-threaded. Which is why I was going to make the ConfigureAwait(false) the default in the GetBytes method instead so users on systems with pinned update threads (IIS + WPF) don't deadlock. It's still doing the forbidden wrapping of an async method. But in a way that will produce fewer issues from IIS/WPF users.

**Comment by MaxBarraclough** [comment]
You're right of course that purely async code is ideal, but I don't see anything preventing us satisfying the synchronous `DeriveBytes#GetBytes(Int32)` method. The fact that the implementation uses multi-threading doesn't prevent us from providing a synchronous method.

My existing ASP.Net code was purely synchronous, and making my code asynchronous would have been a great deal of work for little payoff.

I'm pretty confident your code fragment there will still deadlock.

The `Task#ConfigureAwait` method doesn't modify its `Task` instance, instead it returns a `ConfiguredTaskAwaitable` instance, which is intended to be used with the `await` keyword. It's not intended to be used with the `Result` property, which is of course blocking, unlike `await`.

In your code-fragment, the `ConfigureAwait` call is dead, as the returned `ConfiguredTaskAwaitable` instance is discarded.

The correct solution is to do as Stephen Toub recommends, and have `GetBytesAsync` run on the thread-pool, and *not* on the caller thread. This has to be done explicitly, such as with the `System.Threading.Tasks.Task.Run` method, as Toub shows.

Perhaps the associated thread-marshaling could be avoided by using Toub's *Avoid Unnecessary Marshaling* approach instead, but that would presumably be a much deeper (and more error-prone) change.

**Comment by MaxBarraclough** [comment]
Bump. This bug is a real killer.

**Comment by tbandixen** [comment]
Anything new here?

**Comment by kmaragon** [comment]
The latest version does as Max described now.
