### ISSUE TITLE
Nuget package brings in unnecessary dependencies when used with .NET Framework

### ISSUE THREAD

**Issue by bradgentry** [kmaragon/Konscious.Security.Cryptography#28]
Starting with 1.0.6, the nuget package does not have .NET Framework dependencies specified, so when it is added to a .NET Framework project, it brings in 45 additional Microsoft packages.  Since we don't want to do that, we cannot upgrade from 1.0.5.  (Same issue exists in the Argon2 package)

**Comment by alenas** [comment]
I added 4.6, as that is compatible with net standard 1.3 - I tried with net45 - but then I get error on build, that Array does not have a definition of Empty.

**Comment by bradgentry** [comment]
4.6 works for us.  We are targeting 4.7.2.  Just to confirm, will you also be updating the Argon2 package?

**Comment by bradgentry** [comment]
Sorry, I see that this repo also includes Argon2.  I thought it was just for Blake2.  As long as both Nuget packages have the fix, we should be good to go.

**Comment by kmaragon** [comment]
I published the packages yesterday. Let me know if they look better.

**Comment by bradgentry** [comment]
They appear to be working as expected.  Thanks!

**Comment by kmaragon** [comment]
I forward your thanks to @alenas who actually fixed this. Thanks for the update!

**Comment by alenas** [comment]
;) my pleasure
