### ISSUE TITLE
MemorySize is measured in KiB, not KB as per README

### ISSUE THREAD

**Issue by danrs** [kmaragon/Konscious.Security.Cryptography#31]
The Konscious.Security.Cryptography README claims that argon2 MemorySize is measured in kilobytes. This should say kibibytes instead.

The [reference implementation](https://github.com/p-h-c/phc-winner-argon2) says it uses kibibytes, as do other implementations such as [argon2-cffi](https://argon2-cffi.readthedocs.io/en/stable/api.html).

When comparing output from argon2-cffi and Konscious argon2, the same hash is only produced if both memory size parameters are the same. Using 8192 for Konscious and 8000 (8192KB in KiB) for argon2-cffi does not produce the same hash.

**Comment by kmaragon** [comment]
Glad to have an issue that doesn't take a time commitment that I can't currently make. But I do have 5 min in the morning before work to update a word in the README. Updated. Thanks.
