### ISSUE TITLE
Is this library still active? Should I use it for a new Project?

### ISSUE THREAD

**Issue by litch0** [kmaragon/Konscious.Security.Cryptography#43]

**Comment by samuel-lucas6** [comment]
I'd recommend using [libsodium](https://github.com/tabrath/libsodium-core) because it's considerably faster. Unfortunately, there aren't many maintained libsodium .NET bindings at the moment.

**Comment by keef-cognitiv** [comment]
It's not actively getting new features. But it's somewhat maintained. I will have time to support adding some new things late next year if Microsoft still hasn't added support for these officially. Until then, it's just a matter of MAKING time for critical fixes. Note that as Samuel said, if there's another library that just provides bindings to the official C library, those will just always be faster, at least by a little. This is a pure C# implementation so there's no extra dll/so/dylib shipping, loading, and maintenance required.

**Comment by litch0** [comment]
Ok thanks

**Comment by kmaragon** [comment]
It's not actively getting new features. But it's somewhat maintained. I will have time to support adding some new things late next year if Microsoft still hasn't added support for these officially. Until then, it's just a matter of MAKING time for critical fixes. Note that as Samuel said, if there's another library that just provides bindings to the official C library, those will just always be faster, at least by a little. This is a pure C# implementation so there's no extra dll/so/dylib shipping, loading, and maintenance required.
