### ISSUE TITLE
If using System.Numerics.Vectors version other than 4.1.1, fails with File Not Found

### ISSUE THREAD

**Issue by SparkDustJoe** [kmaragon/Konscious.Security.Cryptography#9]
It seems that Blake2 is tied specifically to that version.  If an update to the System.Numerics.Vectors package is installed instead of 4.1.1, all of Argon2 breaks down.  The linker must be tightly coupled with the full explicit assembly name.

**Comment by kmaragon** [comment]
As you can see, I've updated it to look for 4.*

**Comment by SparkDustJoe** [comment]
Looks like it's fixed 👍
